name: build-all

on:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Rust cache
      - uses: Swatinem/rust-cache@v1

      - run: |
          sudo apt update
          sudo apt install -y gcc-arm-linux-gnueabi
          sudo apt install -y gcc-arm-linux-gnueabihf
          sudo apt install -y gcc-aarch64-linux-gnu

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Rename
        env:
          TARGET: ${{ matrix.target }}
        run: mv target/$TARGET/release/wol target/$TARGET/release/wol-$TARGET

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wol-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/wol-${{ matrix.target }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Rust cache
      - uses: Swatinem/rust-cache@v1

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Rename
        run: |
          mv target/release/wol.exe target/release/wol-windows-amd64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wol-windows-amd64
          path: target/release/wol-*

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Rust cache
      - uses: Swatinem/rust-cache@v1

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Rename
        run: mv target/release/wol target/release/wol-macos-$(uname -m)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wol-macos-amd64
          path: target/release/wol-*
