name: draft-release

on:
  push:
    tags:
      - "v*"

jobs:
  build-all:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - build-all
    steps:
      - name: Download all artifact
        uses: actions/download-artifact@v2
        with:
          path: .

      - name: Development release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: true
          files: |
            ./*/*

