name: main-build

on:
  push:
    branches:
      - main

jobs:
  build-all:
    uses: ./.github/workflows/build.yml

  development-release:
    runs-on: ubuntu-latest
    needs:
      - build-all
    steps:
      - name: Download all artifact
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Development release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Development"
          prerelease: true
          draft: false
          files: |
            ./**
